# Evaluate bo20 retrieval recall accuracy with Docling and Milvus

In this notebook, we'll get the end-to-end recall accuracy of a retrieval pipeline made up of Docling's extraction and embedding tasks and a Milvus vector database (VDB).

Refer to the [Download Bo20 and Bo767](digital_corpora_download.ipynb) notebook to fetch the PDF documents.
In this script, you just need the small dataset **Bo20** with 20 PDFs. Since the dataset is small, the notebook uses [Milvus Lite](https://milvus.io/docs/milvus_lite.md) as vector database.

## Settings

### Environment and dependencies

Create and activate a dedicated environment:

```shell
uv venv --python 3.12 .venv && source .venv/bin/activate && uv pip install ipykernel --upgrade
```

Install the depdencies:

In [69]:
import os
import logging
logging.getLogger().setLevel(logging.WARNING)

os.environ["TOKENIZERS_PARALLELISM"] = "false"

! uv pip install -q --upgrade docling ipython ipywidgets "pymilvus[milvus-lite]" openai

## Convertion & Ingestion

In [ ]:
# Fetch the files
from pathlib import Path

pdf_files = list(Path("../data/bo20").rglob("*.pdf"))

In [ ]:
# Convert with Docling (standard pipeline)
import time
from docling_core.types import DoclingDocument
from docling.datamodel.base_models import ConversionStatus
from docling.document_converter import DocumentConverter

converter = DocumentConverter()
start_time = time.time()
conv_results = converter.convert_all(pdf_files, raises_on_error=False)
docs: list[DoclingDocument] = [item.document for item in conv_results if item.status == ConversionStatus.SUCCESS]
end_time = time.time() - start_time

print(f"Converted {len(docs)} out of {len(pdf_files)} files in {end_time:.2f} seconds.")

2025-11-25 11:25:37,382 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:25:37,415 - INFO - Going to convert document batch...
2025-11-25 11:25:37,415 - INFO - Initializing pipeline for StandardPdfPipeline with options hash 44ae89a68fc272bc7889292e9b5a1bad
2025-11-25 11:25:37,420 - INFO - Loading plugin 'docling_defaults'
2025-11-25 11:25:37,424 - INFO - Registered picture descriptions: ['vlm', 'api']
2025-11-25 11:25:37,427 - INFO - Loading plugin 'docling_defaults'
2025-11-25 11:25:37,440 - INFO - Registered ocr engines: ['auto', 'easyocr', 'ocrmac', 'rapidocr', 'tesserocr', 'tesseract']
2025-11-25 11:25:41,806 - INFO - Auto OCR model selected ocrmac.
2025-11-25 11:25:41,815 - INFO - Accelerator device: 'mps'
2025-11-25 11:25:51,322 - INFO - Accelerator device: 'mps'
2025-11-25 11:25:51,823 - INFO - Processing document 1238975.pdf
2025-11-25 11:25:55,859 - INFO - Finished converting document 1238975.pdf in 18.48 sec.
2025-11-25 11:25:55,861 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:25:55,864 - INFO - Going to convert document batch...
2025-11-25 11:25:55,865 - INFO - Processing document 2132230.pdf
2025-11-25 11:25:56,445 - INFO - Finished converting document 2132230.pdf in 0.59 sec.
2025-11-25 11:25:56,447 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:25:56,450 - INFO - Going to convert document batch...
2025-11-25 11:25:56,450 - INFO - Processing document 1598224.pdf
2025-11-25 11:26:17,202 - INFO - Finished converting document 1598224.pdf in 20.76 sec.
2025-11-25 11:26:17,204 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:26:17,208 - INFO - Going to convert document batch...
2025-11-25 11:26:17,209 - INFO - Processing document 1422550.pdf
2025-11-25 11:26:26,103 - INFO - Finished converting document 1422550.pdf in 8.90 sec.
2025-11-25 11:26:26,106 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:26:26,108 - INFO - Going to convert document batch...
2025-11-25 11:26:26,109 - INFO - Processing document 1479052.pdf
2025-11-25 11:26:26,768 - INFO - Finished converting document 1479052.pdf in 0.67 sec.
2025-11-25 11:26:26,771 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:26:26,777 - INFO - Going to convert document batch...
2025-11-25 11:26:26,778 - INFO - Processing document 1620834.pdf
2025-11-25 11:26:38,548 - INFO - Finished converting document 1620834.pdf in 11.78 sec.
2025-11-25 11:26:38,549 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:26:38,555 - INFO - Going to convert document batch...
2025-11-25 11:26:38,555 - INFO - Processing document 2151932.pdf
2025-11-25 11:26:49,219 - INFO - Finished converting document 2151932.pdf in 10.67 sec.
2025-11-25 11:26:49,222 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:26:49,225 - INFO - Going to convert document batch...
2025-11-25 11:26:49,226 - INFO - Processing document 1061225.pdf
2025-11-25 11:27:01,005 - INFO - Finished converting document 1061225.pdf in 11.79 sec.
2025-11-25 11:27:01,008 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:01,013 - INFO - Going to convert document batch...
2025-11-25 11:27:01,013 - INFO - Processing document 2049749.pdf
2025-11-25 11:27:08,250 - INFO - Finished converting document 2049749.pdf in 7.25 sec.
2025-11-25 11:27:08,254 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:08,261 - INFO - Going to convert document batch...
2025-11-25 11:27:08,261 - INFO - Processing document 2127440.pdf
2025-11-25 11:27:10,360 - INFO - Finished converting document 2127440.pdf in 2.11 sec.
2025-11-25 11:27:10,364 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:10,367 - INFO - Going to convert document batch...
2025-11-25 11:27:10,367 - INFO - Processing document 1016445.pdf
2025-11-25 11:27:10,979 - INFO - Finished converting document 1016445.pdf in 0.62 sec.
2025-11-25 11:27:10,982 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:10,985 - INFO - Going to convert document batch...
2025-11-25 11:27:10,986 - INFO - Processing document 2399488.pdf
2025-11-25 11:27:11,761 - INFO - Finished converting document 2399488.pdf in 0.78 sec.
2025-11-25 11:27:11,762 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:11,764 - INFO - Going to convert document batch...
2025-11-25 11:27:11,765 - INFO - Processing document 1666072.pdf
2025-11-25 11:27:12,705 - INFO - Finished converting document 1666072.pdf in 0.94 sec.
2025-11-25 11:27:12,706 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:12,713 - INFO - Going to convert document batch...
2025-11-25 11:27:12,714 - INFO - Processing document 1037700.pdf
2025-11-25 11:27:20,349 - INFO - Finished converting document 1037700.pdf in 7.64 sec.
2025-11-25 11:27:20,350 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:20,354 - INFO - Going to convert document batch...
2025-11-25 11:27:20,355 - INFO - Processing document 1177640.pdf
2025-11-25 11:27:35,315 - INFO - Finished converting document 1177640.pdf in 14.97 sec.
2025-11-25 11:27:35,317 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:27:35,350 - INFO - Going to convert document batch...
2025-11-25 11:27:35,351 - INFO - Processing document 1375277.pdf
2025-11-25 11:28:09,353 - INFO - Finished converting document 1375277.pdf in 34.04 sec.
2025-11-25 11:28:09,355 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:28:09,357 - INFO - Going to convert document batch...
2025-11-25 11:28:09,357 - INFO - Processing document 2189929.pdf
2025-11-25 11:28:11,091 - INFO - Finished converting document 2189929.pdf in 1.74 sec.
2025-11-25 11:28:11,096 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:28:11,101 - INFO - Going to convert document batch...
2025-11-25 11:28:11,101 - INFO - Processing document 1043219.pdf
2025-11-25 11:28:11,526 - INFO - Finished converting document 1043219.pdf in 0.43 sec.
2025-11-25 11:28:11,528 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:28:11,531 - INFO - Going to convert document batch...
2025-11-25 11:28:11,531 - INFO - Processing document 1690009.pdf
2025-11-25 11:28:20,690 - INFO - Finished converting document 1690009.pdf in 9.16 sec.
2025-11-25 11:28:20,692 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-11-25 11:28:20,849 - INFO - Going to convert document batch...
2025-11-25 11:28:20,850 - INFO - Processing document 2062555.pdf
2025-11-25 11:30:02,463 - INFO - Finished converting document 2062555.pdf in 101.77 sec.

Converted 20 out of 20 files in 265.09 seconds.

In [5]:
# Optional: save results
import os
import pickle

with open("bo20_docling_results.pkl", "wb") as filehandler:
    pickle.dump(docs, filehandler)

# Optional: save documents in JSON format
os.makedirs("docs", exist_ok=True)
for item in docs:
    item.save_as_json((Path("docs") / item.origin.filename).with_suffix(".json"))

In [6]:
# Optional: load results
import pickle

with open("bo20_docling_results.pkl", "rb") as filehandler:
    docs = pickle.load(filehandler)

In [ ]:
# Set up the embeddings with OpenAI and Nvidia API
from typing import Literal
from openai import OpenAI

client = OpenAI(
  api_key="nvapi-xxxxx",
  base_url="https://integrate.api.nvidia.com/v1"
)

def emb_text(text: str, input_type: Literal["passage", "query"]):
    return (
        client.embeddings.create(
            model="nvidia/llama-3.2-nv-embedqa-1b-v2",
            encoding_format="float",
            extra_body={"input_type": input_type, "truncate": "NONE"},
            input=text,
        ).data[0].embedding
    )

test_embedding = emb_text("This is a test", input_type="passage")
embedding_dim = len(test_embedding)
print(f"Embedding size is {embedding_dim}")

2025-11-25 11:30:18,455 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"

Embedding size is 2048

In [8]:
# Set up Docling's chunkers: page chunker and hybrid chunker using llama 3.2 tokenizer
from transformers import AutoTokenizer
from docling.chunking import HybridChunker
from docling_core.transforms.chunker import PageChunker
from docling_core.transforms.chunker.tokenizer.huggingface import HuggingFaceTokenizer

page_chunker = PageChunker()

from_pretrained = AutoTokenizer.from_pretrained("nvidia/llama-nemotron-embed-1b-v2")
# max tokens needs to be set explicitly: 8192 tokens accoring to model card
tokenizer = HuggingFaceTokenizer(
    tokenizer=from_pretrained,
    max_tokens = 8192
)
hybrid_chunker = HybridChunker(tokenizer=tokenizer)

In [ ]:
# Chunk text
import statistics
from docling_core.transforms.chunker import DocChunk

page_chunks: list[DocChunk] = []
page_num: list[str] = []
hybrid_chunks: list[DocChunk] = []
hybrid_num: list[int] = []
for doc in docs:
    doc_chunks = list(hybrid_chunker.chunk(doc))
    hybrid_chunks.extend(doc_chunks)
    hybrid_num.append(len(doc_chunks))

    doc_chunks = list(page_chunker.chunk(doc))
    page_chunks.extend(doc_chunks)
    page_num.append(len(doc_chunks))


print(f"Hybrid chunks in {len(docs)} docs: {sum(hybrid_num)=}, {statistics.mean(hybrid_num)=}, {statistics.median(hybrid_num)=}, {max(hybrid_num)=}, {min(hybrid_num)=}")
print(f"Page chunks in {len(docs)} docs: {sum(page_num)=}, {statistics.mean(page_num)=}, {statistics.median(page_num)=}, {max(page_num)=}, {min(page_num)=}")

Hybrid chunks in 20 docs: sum(hybrid_num)=475, statistics.mean(hybrid_num)=23.75, statistics.median(hybrid_num)=17.0, max(hybrid_num)=99, min(hybrid_num)=2
Page chunks in 20 docs: sum(page_num)=436, statistics.mean(page_num)=21.8, statistics.median(page_num)=15.5, max(page_num)=116, min(page_num)=1

In [ ]:
# Set ingestion: for this simple dataset, we will use Milvus Lite
# Only dense embeddings (to be aligned with bo20_recall.ipynb)
from pymilvus import MilvusClient

#CONSISTENCY = "Bounded"
CONSISTENCY = "Strong"  # only value supported by Milvus Lite
INDEX_TYPE = "FLAT"
METRIC_TYPE = "L2"

milvus_client = MilvusClient(uri="./milvuslite_docling.db")
collection_base = "bo20_docling"
collections = {"section", "page"}
for item in collections:
    collection_name = f"{collection_base}_{item}"
    if milvus_client.has_collection(collection_name):
        milvus_client.drop_collection(collection_name)

    # taking milvus index parameters from NV Ingest client
    milvus_client.create_collection(
        collection_name=collection_name,
        dimension=embedding_dim,
        metric_type=METRIC_TYPE,
        index_type=INDEX_TYPE,
        consistency_level=CONSISTENCY,
    )

In [28]:
# Insert data
import pickle
from tqdm import tqdm

for item in collections:
    data = []
    chunks = hybrid_chunks if item == "section" else page_chunks
    for i, chunk in enumerate(tqdm(chunks, desc=f"Embedding {item} chunks")):
        embedding = emb_text(chunk.text, "passage")
        data.append({"id": i, "vector": embedding, "text": chunk.text, "meta": chunk.meta.export_json_dict()})
    milvus_client.insert(collection_name=f"{collection_base}_{item}", data=data)
    # save chunks to disk
    with open(f"{collection_base}_{item}_chunks.pkl", "wb") as f:
        pickle.dump(data, f)

Embedding section chunks:   0%|          | 0/475 [00:00<?, ?it/s]2025-11-25 14:12:53,867 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   0%|          | 1/475 [00:00<04:22,  1.81it/s]2025-11-25 14:12:54,197 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   0%|          | 2/475 [00:00<03:17,  2.39it/s]2025-11-25 14:12:54,467 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   1%|          | 3/475 [00:01<02:46,  2.83it/s]2025-11-25 14:12:54,744 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   1%|          | 4/475 [00:01<02:30,  3.13it/s]2025-11-25 14:12:54,907 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   1%|          | 5/475 [00:01<02:03,  3.79it/s]2025-11-25 14:12:55,084 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   1%|▏         | 6/475 [00:01<01:50,  4.23it/s]2025-11-25 14:12:55,273 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   1%|▏         | 7/475 [00:01<01:41,  4.59it/s]2025-11-25 14:12:55,445 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   2%|▏         | 8/475 [00:02<01:36,  4.85it/s]2025-11-25 14:12:55,694 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   2%|▏         | 9/475 [00:02<01:42,  4.55it/s]2025-11-25 14:12:55,862 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   2%|▏         | 10/475 [00:02<01:33,  4.96it/s]2025-11-25 14:12:56,033 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   2%|▏         | 11/475 [00:02<01:30,  5.13it/s]2025-11-25 14:12:56,214 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   3%|▎         | 12/475 [00:02<01:26,  5.34it/s]2025-11-25 14:12:56,375 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   3%|▎         | 13/475 [00:03<01:23,  5.54it/s]2025-11-25 14:12:56,540 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   3%|▎         | 14/475 [00:03<01:22,  5.60it/s]2025-11-25 14:12:56,710 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   3%|▎         | 15/475 [00:03<01:19,  5.78it/s]2025-11-25 14:12:56,875 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   3%|▎         | 16/475 [00:03<01:19,  5.77it/s]2025-11-25 14:12:57,049 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   4%|▎         | 17/475 [00:03<01:18,  5.85it/s]2025-11-25 14:12:57,214 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   4%|▍         | 18/475 [00:03<01:17,  5.92it/s]2025-11-25 14:12:57,381 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   4%|▍         | 19/475 [00:04<01:20,  5.68it/s]2025-11-25 14:12:57,570 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   4%|▍         | 20/475 [00:04<01:18,  5.79it/s]2025-11-25 14:12:57,689 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:12:57,690 - INFO - Retrying request to /embeddings in 0.446680 seconds
2025-11-25 14:12:58,257 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   4%|▍         | 21/475 [00:04<02:29,  3.04it/s]2025-11-25 14:12:58,431 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   5%|▍         | 22/475 [00:05<02:07,  3.56it/s]2025-11-25 14:12:58,602 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   5%|▍         | 23/475 [00:05<01:52,  4.03it/s]2025-11-25 14:12:58,797 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   5%|▌         | 24/475 [00:05<01:45,  4.28it/s]2025-11-25 14:12:58,923 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:12:58,923 - INFO - Retrying request to /embeddings in 0.382498 seconds
2025-11-25 14:12:59,433 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   5%|▌         | 25/475 [00:06<02:38,  2.84it/s]2025-11-25 14:12:59,598 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   5%|▌         | 26/475 [00:06<02:13,  3.36it/s]2025-11-25 14:12:59,766 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   6%|▌         | 27/475 [00:06<01:55,  3.89it/s]2025-11-25 14:12:59,927 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   6%|▌         | 28/475 [00:06<01:42,  4.36it/s]2025-11-25 14:13:00,073 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:00,073 - INFO - Retrying request to /embeddings in 0.375310 seconds
2025-11-25 14:13:00,570 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   6%|▌         | 29/475 [00:07<02:38,  2.82it/s]2025-11-25 14:13:00,740 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   6%|▋         | 30/475 [00:07<02:12,  3.37it/s]2025-11-25 14:13:00,908 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   7%|▋         | 31/475 [00:07<01:55,  3.84it/s]2025-11-25 14:13:01,085 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   7%|▋         | 32/475 [00:07<01:43,  4.29it/s]2025-11-25 14:13:01,203 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:01,204 - INFO - Retrying request to /embeddings in 0.489669 seconds
2025-11-25 14:13:01,816 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   7%|▋         | 33/475 [00:08<02:49,  2.61it/s]2025-11-25 14:13:01,986 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   7%|▋         | 34/475 [00:08<02:21,  3.11it/s]2025-11-25 14:13:02,160 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   7%|▋         | 35/475 [00:08<02:00,  3.64it/s]2025-11-25 14:13:02,329 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   8%|▊         | 36/475 [00:09<01:47,  4.08it/s]2025-11-25 14:13:02,453 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:02,454 - INFO - Retrying request to /embeddings in 0.386914 seconds
2025-11-25 14:13:02,966 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   8%|▊         | 37/475 [00:09<02:37,  2.78it/s]2025-11-25 14:13:03,128 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   8%|▊         | 38/475 [00:09<02:11,  3.32it/s]2025-11-25 14:13:03,296 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   8%|▊         | 39/475 [00:09<01:54,  3.80it/s]2025-11-25 14:13:03,466 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   8%|▊         | 40/475 [00:10<01:41,  4.29it/s]2025-11-25 14:13:03,586 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:03,587 - INFO - Retrying request to /embeddings in 0.454351 seconds
2025-11-25 14:13:04,166 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   9%|▊         | 41/475 [00:10<02:42,  2.67it/s]2025-11-25 14:13:04,339 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   9%|▉         | 42/475 [00:11<02:15,  3.20it/s]2025-11-25 14:13:04,505 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   9%|▉         | 43/475 [00:11<01:55,  3.72it/s]2025-11-25 14:13:04,676 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   9%|▉         | 44/475 [00:11<01:43,  4.15it/s]2025-11-25 14:13:04,797 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:04,798 - INFO - Retrying request to /embeddings in 0.419830 seconds
2025-11-25 14:13:05,343 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:   9%|▉         | 45/475 [00:12<02:37,  2.72it/s]2025-11-25 14:13:05,512 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  10%|▉         | 46/475 [00:12<02:12,  3.23it/s]2025-11-25 14:13:05,684 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  10%|▉         | 47/475 [00:12<01:54,  3.75it/s]2025-11-25 14:13:05,849 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  10%|█         | 48/475 [00:12<01:40,  4.24it/s]2025-11-25 14:13:05,967 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:05,968 - INFO - Retrying request to /embeddings in 0.477759 seconds
2025-11-25 14:13:06,567 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  10%|█         | 49/475 [00:13<02:43,  2.61it/s]2025-11-25 14:13:06,739 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  11%|█         | 50/475 [00:13<02:14,  3.15it/s]2025-11-25 14:13:06,906 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  11%|█         | 51/475 [00:13<01:56,  3.65it/s]2025-11-25 14:13:07,078 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  11%|█         | 52/475 [00:13<01:42,  4.14it/s]2025-11-25 14:13:07,195 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:07,196 - INFO - Retrying request to /embeddings in 0.480542 seconds
2025-11-25 14:13:07,797 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  11%|█         | 53/475 [00:14<02:42,  2.60it/s]2025-11-25 14:13:07,965 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  11%|█▏        | 54/475 [00:14<02:15,  3.11it/s]2025-11-25 14:13:08,136 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  12%|█▏        | 55/475 [00:14<01:55,  3.65it/s]2025-11-25 14:13:08,305 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  12%|█▏        | 56/475 [00:14<01:42,  4.09it/s]2025-11-25 14:13:08,428 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:08,428 - INFO - Retrying request to /embeddings in 0.428987 seconds
2025-11-25 14:13:08,977 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  12%|█▏        | 57/475 [00:15<02:35,  2.69it/s]2025-11-25 14:13:09,144 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  12%|█▏        | 58/475 [00:15<02:09,  3.23it/s]2025-11-25 14:13:09,310 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  12%|█▏        | 59/475 [00:15<01:51,  3.72it/s]2025-11-25 14:13:09,483 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  13%|█▎        | 60/475 [00:16<01:38,  4.22it/s]2025-11-25 14:13:09,597 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:09,598 - INFO - Retrying request to /embeddings in 0.395460 seconds
2025-11-25 14:13:10,118 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  13%|█▎        | 61/475 [00:16<02:28,  2.79it/s]2025-11-25 14:13:10,292 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  13%|█▎        | 62/475 [00:16<02:04,  3.32it/s]2025-11-25 14:13:10,458 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  13%|█▎        | 63/475 [00:17<01:47,  3.82it/s]2025-11-25 14:13:10,638 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  13%|█▎        | 64/475 [00:17<01:38,  4.19it/s]2025-11-25 14:13:10,761 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:10,762 - INFO - Retrying request to /embeddings in 0.430293 seconds
2025-11-25 14:13:11,317 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  14%|█▎        | 65/475 [00:17<02:31,  2.71it/s]2025-11-25 14:13:11,486 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  14%|█▍        | 66/475 [00:18<02:07,  3.22it/s]2025-11-25 14:13:11,657 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  14%|█▍        | 67/475 [00:18<01:48,  3.75it/s]2025-11-25 14:13:11,818 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  14%|█▍        | 68/475 [00:18<01:36,  4.24it/s]2025-11-25 14:13:11,938 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:11,939 - INFO - Retrying request to /embeddings in 0.455447 seconds
2025-11-25 14:13:12,518 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  15%|█▍        | 69/475 [00:19<02:33,  2.65it/s]2025-11-25 14:13:12,693 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  15%|█▍        | 70/475 [00:19<02:06,  3.20it/s]2025-11-25 14:13:12,856 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  15%|█▍        | 71/475 [00:19<01:49,  3.68it/s]2025-11-25 14:13:13,028 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  15%|█▌        | 72/475 [00:19<01:36,  4.19it/s]2025-11-25 14:13:13,147 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:13,147 - INFO - Retrying request to /embeddings in 0.390096 seconds
2025-11-25 14:13:13,662 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  15%|█▌        | 73/475 [00:20<02:23,  2.80it/s]2025-11-25 14:13:13,826 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  16%|█▌        | 74/475 [00:20<02:00,  3.32it/s]2025-11-25 14:13:13,995 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  16%|█▌        | 75/475 [00:20<01:43,  3.86it/s]2025-11-25 14:13:14,162 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  16%|█▌        | 76/475 [00:20<01:33,  4.29it/s]2025-11-25 14:13:14,331 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  16%|█▌        | 77/475 [00:21<01:24,  4.69it/s]2025-11-25 14:13:14,454 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:14,455 - INFO - Retrying request to /embeddings in 0.383014 seconds
2025-11-25 14:13:14,965 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  16%|█▋        | 78/475 [00:21<02:14,  2.96it/s]2025-11-25 14:13:15,131 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  17%|█▋        | 79/475 [00:21<01:54,  3.45it/s]2025-11-25 14:13:15,303 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  17%|█▋        | 80/475 [00:21<01:39,  3.97it/s]2025-11-25 14:13:15,468 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  17%|█▋        | 81/475 [00:22<01:29,  4.40it/s]2025-11-25 14:13:15,590 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:15,591 - INFO - Retrying request to /embeddings in 0.393893 seconds
2025-11-25 14:13:16,101 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  17%|█▋        | 82/475 [00:22<02:16,  2.88it/s]2025-11-25 14:13:16,272 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  17%|█▋        | 83/475 [00:22<01:55,  3.40it/s]2025-11-25 14:13:16,574 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  18%|█▊        | 84/475 [00:23<01:57,  3.33it/s]2025-11-25 14:13:16,748 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 200 OK"
Embedding section chunks:  18%|█▊        | 85/475 [00:23<01:41,  3.86it/s]2025-11-25 14:13:16,865 - INFO - HTTP Request: POST https://integrate.api.nvidia.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
2025-11-25 14:13:16,866 - INFO - Retrying request to /embeddings in 0.397938 seconds

## Evaluation

In [86]:
# Supporting function to calculate the evaluation metrics: Recal@K, only for questions on bo20 documents
import numpy as np
import pandas as pd
from collections import defaultdict

def get_recall_scores(query_df: pd.DataFrame, collection_name: str):
    # filter the queries on PDFs for this collection only
    pdf_names = [item.name for item in pdf_files]
    eval_queries = list(zip(
        query_df[query_df["pdf"].isin(pdf_names)]["query"].index,
        query_df[query_df["pdf"].isin(pdf_names)]["query"]))
    print(f"Evaluation metrics on {len(eval_queries)} questions")
    if len(eval_queries) == 0:
        return

    hits = defaultdict(list)
    query_embeddings = [emb_text(question[1], "query") for question in eval_queries]
    all_answers = milvus_client.search(
        collection_name=collection_name,
        data=query_embeddings,
        limit=10,
        consistency_level=CONSISTENCY,
        search_params={"ef": 100},
        output_fields=["meta"],
    )
    for idx, query in enumerate(eval_queries):
        expected_pdf_page = query_df["pdf_page"][query[0]]
        retrieved_answers = all_answers[idx]
        retrieved_pdfs = [result['entity']['meta']['origin']['filename'].removesuffix('.pdf') for result in retrieved_answers]
        # Warning: we assume that the first provenance of the first doc item holds the 'right' page number
        # Docling pages are 1-based
        retrieved_pages = [result['entity']['meta']['doc_items'][0]['prov'][0]['page_no'] - 1 for result in retrieved_answers]
        retrieved_pdf_pages = [f"{pdf}_{page}" for pdf, page in zip(retrieved_pdfs, retrieved_pages)]

        for k in [1, 3, 5, 10]:
            hits[k].append(expected_pdf_page in retrieved_pdf_pages[:k])
    
    for k in hits:
        print(f'  - Recall @{k}: {np.mean(hits[k]) :.3f}')

### Text Recall

In [87]:
import pandas as pd

df_query = pd.read_csv('../data/text_query_answer_gt_page.csv')
#df_query.pdf = df_query.pdf.apply(lambda x: x.replace('.pdf',''))
df_query['pdf_page'] = df_query.apply(lambda x: f"{x.pdf.removesuffix('.pdf')}_{x.gt_page}", axis=1) 
df_query

,pdf,query,answer,gt_page,pdf_page
0,1102434.pdf,How much was the ARtillery Intelligence projec...,$4.2 billion,19,1102434_19
1,1102434.pdf,How much revenue of AR advertising is expected...,$8.8 billion,3,1102434_3
2,1096078.pdf,What types of statistics were utilized by Rein...,descriptive statistics,3,1096078_3
3,1054125.pdf,What was the maximum amount requested for cond...,"$35,000.00",1,1054125_1
4,1246906.pdf,What is the median household income for the Ci...,"$53,278",7,1246906_7
...,...,...,...,...,...
483,2089825.pdf,Under the Climate Action and Low Carbon Develo...,Denis Naughten TD,0,2089825_0
484,2089825.pdf,How many organizations make up Stop Climate Ch...,30,5,2089825_5
485,2098077.pdf,What is the maximum length of Sai Yok bent-­to...,2.4 inches,1,2098077_1
486,2098077.pdf,What characteristic sets the Sai Yok Bent-toed...,enlarged thigh scales,1,2098077_1
487,2098077.pdf,What is the name of the new gecko species that...,Sai Yok bent­toed gecko ( Cyrtodactylus saiyok ),0,2098077_0

In [88]:
for item in collections:
    collection_name = f"{collection_base}_{item}"
    print(f"Evaluation of {collection_name} on Text")
    get_recall_scores(df_query, collection_name)

Evaluation of bo20_docling_section on Text
Evaluation metrics on 3 questions
  - Recall @1: 1.000
  - Recall @3: 1.000
  - Recall @5: 1.000
  - Recall @10: 1.000
Evaluation of bo20_docling_page on Text
Evaluation metrics on 3 questions
  - Recall @1: 1.000
  - Recall @3: 1.000
  - Recall @5: 1.000
  - Recall @10: 1.000

### Table recall

In [89]:
df_query = pd.read_csv('../data/table_queries_cleaned_235.csv')[['query','pdf','page','table']]
df_query['pdf_page'] = df_query.apply(lambda x: f"{x.pdf}_{x.page}", axis=1)
df_query

,query,pdf,page,table,pdf_page
0,How much did Pendleton County spend out of the...,1003421,2,1003421_2_0,1003421_2
1,How many units are occupied by single families...,1008059,6,1008059_6_1,1008059_6
2,"In the Klamath county, what is the total valua...",1008059,6,1008059_6_1,1008059_6
3,How much did Nalco pay GRIDCO for electricity ...,1011810,21,1011810_21_0,1011810_21
4,How much coal is used at Alumina refinery of N...,1011810,21,1011810_21_2,1011810_21
...,...,...,...,...,...
230,How much is the rental income from water plant...,2407280,30,2407280_30_0,2407280_30
231,In 2020 how much were the supplemental taxes f...,2415001,65,not detected,2415001_65
232,"As of 2020, what is the total of collections a...",2415001,65,not detected,2415001_65
233,What was the net gain from the operations of t...,2416020,84,2416020_84_0,2416020_84
234,What was the highest operating expense in Nove...,2416020,84,2416020_84_0,2416020_84

In [90]:
for item in collections:
    collection_name = f"{collection_base}_{item}"
    print(f"Evaluation of {collection_name} on Tables")
    get_recall_scores(df_query, collection_name)

Evaluation of bo20_docling_section on Tables
Evaluation metrics on 0 questions
Evaluation of bo20_docling_page on Tables
Evaluation metrics on 0 questions